version: '3.8'

services:
    api:
        build: 
            dockerfile: Dockerfile
            context: .
        image: mongmang/monghub:first-deploy
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
            NODE_ENV: development
            PORT: 3000
        ports:
            - "3000:3000"
    postgres:
        image: postgres:14.3
        expose:
            - 5432
        ports:
            - 5432:5432
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
