import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { SearchParameter } from "src/core/shared/models/search-param-model";

export class SearchStudentDto extends SearchParameter {
    studentCode?:string
    firstname?:string
    lastname?:string
}
export class StudentDto {
    studentCode:string
    status:number
    title:number
    firstname:string
    lastname:string
    gendar:number
    birthDate:Date
    nationality:string
    ethnicity:string
    religion:string
    email:string
    phoneNumber:string
    specialAbility:string
    birthHospitalId:number
    birthCountryId:number
    birthSubDistrictId:string
    birthDistrictId:string
    birthProvinceId:string
    address:string
    countryId:number
    subDistrictId:number
    districtId:number
    provinceId:number
    postCode:string
    contractAddress:string
    contractCountryId:number
    contractSubDistrictId:number
    contractDistrictId:number
    contractProvinceId:number
    contractPostCode:string
    oldSchoolId:number
    className:number
    mentorTeacherFirstId:number
    mentorTeacherSecondId:number
    closeFreindInClassId:number
    closeFreindOtherClassId:number
    bloodType:number
    liveWith:number
    parentStatus:number
    imageProfile:string
    room:number
} 
export class CreateStudentDto extends StudentDto{
    studentCode:string
    status:number
    title:number
    firstname:string
    lastname:string
    gendar:number
    birthDate:Date
    nationality:string
    ethnicity:string
    religion:string
    email:string
    phoneNumber:string
    specialAbility:string
    birthHospitalId:number
    birthCountryId:number
    birthSubDistrictId:string
    birthDistrictId:string
    birthProvinceId:string
    address:string
    countryId:number
    subDistrictId:number
    districtId:number
    provinceId:number
    postCode:string
    contractAddress:string
    contractCountryId:number
    contractSubDistrictId:number
    contractDistrictId:number
    contractProvinceId:number
    contractPostCode:string
    oldSchoolId:number
    className:number
    mentorTeacherFirstId:number
    mentorTeacherSecondId:number
    closeFreindInClassId:number
    closeFreindOtherClassId:number
    bloodType:number
    liveWith:number
    parentStatus:number
    imageProfile:string
    room:number
}
export class UpdateStudentDto extends StudentDto{
    studentCode:string
    status:number
    title:number
    firstname:string
    lastname:string
    gendar:number
    birthDate:Date
    nationality:string
    ethnicity:string
    religion:string
    email:string
    phoneNumber:string
    specialAbility:string
    birthHospitalId:number
    birthCountryId:number
    birthSubDistrictId:string
    birthDistrictId:string
    birthProvinceId:string
    address:string
    countryId:number
    subDistrictId:number
    districtId:number
    provinceId:number
    postCode:string
    contractAddress:string
    contractCountryId:number
    contractSubDistrictId:number
    contractDistrictId:number
    contractProvinceId:number
    contractPostCode:string
    oldSchoolId:number
    className:number
    mentorTeacherFirstId:number
    mentorTeacherSecondId:number
    closeFreindInClassId:number
    closeFreindOtherClassId:number
    bloodType:number
    liveWith:number
    parentStatus:number
    imageProfile:string
    room:number
}
