export const RESULT_HELP_TYPE =[
    {
      label: 'ดีขึ้น',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ไม่ดีขึ้น',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
  export const SENT_TYPE =[
    {
      label: 'นัดหมายครั้งต่อไป',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ประสานผู้ปกครอง',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ส่งต่อหน่วยงานภายนอก',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ส่งต่อครูแนะแนว',
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ส่งต่องานพยาบาล',
      value: 5,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ส่งต่องานปกครอง',
      value: 6,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
 
  export const RESULT_TYPE =[
    {
      label: 'นักเรียนสามารถแก้ปัญหาได้',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'นักเรียนไม่สามารถแก้ปัญหาได้',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
  export const STORY_TYPE =[
    {
      label: 'การเรียน',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ส่วนตัวและสังคม',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'การศึกษาและอาชีพ',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
  export const CONSULTANT_TYPE =[
    {
      label: 'ENUM.FACE_TO_FACE',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.ONLINE',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
  
  
  
  
  
  
  
  export const EYE_OPTION = [
    {
      label: 'ENUM.EYE_NORMAL',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.EYE_SHOT',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.EYE_SLOP',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.EYE_LONG',
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
  export const UESR_TYPE_OPTION = [
    {
      label: 'ENUM.ADMIN',
      value: 'Admin',
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.BUSINESS',
      value: 'Business',
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.HUMAN',
      value: 'Human',
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.ACCOUNT',
      value: 'Account',
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.STUDENT',
      value: 'Student',
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.TEACHER',
      value: 'Teacher',
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ];
  export const STUDENT_FILTER_DROPDOWN = [
    {
      label: 'ENUM.NORMAL_SHORT',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.RISK_SHORT',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.PROBLEM_SHORT',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
  export const PERFOMANCE_TYPE_DROPDOWN = [
    {
      label: 'ENUM.ACADEMIC',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.ART',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.SPORT_E',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.MUSIC',
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.DANCE',
      value: 5,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.CAREER',
      value: 6,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ]
  export const EDUCATION_STATUS = [
    {
      label: 'ENUM.STUDING',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.CONGULATION',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ];
  export const TEACHER_WORK_STATUS = [
    {
      label: 'ENUM.COMPLETE',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.WORKING',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ];
  export const TEACHER_TITLE = [
    {
      label: 'ENUM.MR',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.MRS',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ENUM.OLDMISS',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ];

  
  export const PRACTITIONER_NO = [
    {
      label: "คศ.1",
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "คศ.2",
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "คศ.3",
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "คศ.4",
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
     
  ];
  export const TEACER_POSITION_NAME = [
    {
      label: "ผู้บริหาร",
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "ครู",
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "เจ้าหน้าที่",
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "บุคลากรทางการศึกษา",
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ];
  
  export const TEACHER_STATUS = [
    {
      label: 'สอน',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ออก',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'ย้าย',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: 'เกษียน',
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    }
  
  ];
  export const EDUCATION = [
    {
      label: "ปริญญาเอก",
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "ปริญญาโท",
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "ปริญญาตรี",
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "อนุปริญญา",
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
    {
      label: "อื่นๆ",
      value: 5,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },
  ];
  
  export const GENDAR = [
      {
        label: 'ENUM.MALE',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.FEMALE',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const PARENT_TITLE = [
      {
        label: 'ENUM.OLDMISS',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.MRS',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.MR',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      }
    ];
    export const MOTHER_TITLE = [
      {
        label: 'ENUM.OLDMISS',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.MRS',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      }
    ];
    export const FATHER_TITLE = [

    ];
    export const TITLE_EN = [
      {
        label: 'Mr.',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'Miss',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'Mr.',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'Mrs.',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'Miss',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ]
    export const CLASS_SPECIAL = [
      {
        label: "ห้องเรียนพิเศษ EP",
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "ห้องเรียนพิเศษ ISMEP",
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "ห้องเรียนพิเศษ SMTE",
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "ห้องเรียนพิเศษ วิทยาศาสตร์- คณิตศาสตร์",
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "ห้องเรียนพิเศษ คณิตศาสตร์-ภาษาอังกฤษ",
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "ห้องเรียนพิเศษ ภาษาศาสตร์ - ภาษาอังกฤษ",
        value: 6,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "ห้องเรียนพิเศษ ภาษาศาสตร์ - จีน",
        value: 7,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "ห้องเรียนพิเศษ ภาษาศาสตร์ - ญี่ปุ่น",
        value: 8,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: "อื่นๆ",
        value: 9,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ]
    export const TITLE = [
      {
        label: 'เด็กชาย',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'เด็กหญิง',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'นาย',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'นาง',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'นางสาว',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const STUDENT_STATUS = [
      {
        label: 'กำลังศึกษา',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ลาออก',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'สำเร็จการศึกษา',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'แขวนลอย/พักการเรียน',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      }
    ];
    export const EDIT_REQUEST_STATUS =[
      {
        label: 'ENUM.REQUEST',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.APPROVE',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.REJECT',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ]
    export const BLOOD_TYPE = [
      {
        label: 'A',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'B',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'O',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'AB',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'A-',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'B-',
        value: 6,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'O-',
        value: 7,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'AB-',
        value: 8,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'A+',
        value: 9,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'B+',
        value: 10,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'O+',
        value: 11,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'AB+',
        value: 12,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const LIVE_WITH =[
      {
        label: 'ENUM.DAD_AND_MOM',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.DAD',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.MOM',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.OTHER',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const FAMILY_STATUS =[
      {
        label: 'ENUM.PARENTS_LIVE_TOGATHERS',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.DIVORCE',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.DAD_REMARRY',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.MOM_REMARRY',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.DAD_DIED',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.MOM_DIED',
        value: 6,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const PARENTS_NUTURE_STUDENTS =[
      {
        label: 'ENUM.STRICT',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.INDULGENT',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.USE_REASON',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.NEGLECT',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      }, {
        label: 'ENUM.OTHER',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const FAMILY_MEMBER_RELATIONSHIP =[
      {
        label: 'ENUM.HIGH_RELATIONSHIP',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.NORMAL_RELATIONSHIP',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.LOW_RELATIONSHIP',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
     
    ];
    export const FAMILY_MEET_TIME =[
      {
        label: 'ENUM.MORNIMG',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.NOON',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.SUNSET',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
     {
        label: 'ENUM.OTHER',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const STUDENT_FAMMILY_MEMBER_CLOSEST =[
      {
        label: 'ENUM.DAD',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.MOM',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.OLD_SISTER',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
     {
        label: 'ENUM.YOUNG_SISTER',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.OLD_BROTHER',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
     {
        label: 'ENUM.YOUNG_BROTHER',
        value: 6,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.OTHER',
        value: 7,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const COMMUNITY_ENVIROMENT =[
      {
        label: 'ENUM.SAFE_ENVIROMENT',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.RISK_ENVIROMENT',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
  
    export const VISIT_CARRIES =[
      {
        label: 'ENUM.PRIVATE_CAR',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.SCHOOL_BUS',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.BUS',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.WALK',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.OTHER',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const RESIDENCE_ENVIROMENT =[
      {
        label: 'ENUM.COMMERCIAL_BUILDING',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.ONE_WOOD',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.HALF_BUILD_WOOD',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.ONE_BUILD',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.TWO_WOOD',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.OTHER',
        value: 6,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
  
    export const HOW_GO_SCHOOL =[
      {
        label: 'ENUM.WALK',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.OWN_WITHOUT_PAID',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.BUS_WITH_PAID',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.SCHOOL_BUS_WITH_PAID',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.BICYCLE',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const HOME_SCHOOL_DISTANCE =[
      {
        label: 'ENUM.DISTANCE_ONE',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.DISTANCE_TWO',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.DISTANCE_THREE',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
     {
        label: 'ENUM.DISTANCE_FOUR',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.DISTANCE_FIVE',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
    export const ROUTE_SCHOOL =[
      {
        label: 'ENUM.GENERAL_STOR',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },    
      {
        label: 'ENUM.GAME_STORE',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.FOREST',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
     {
        label: 'ENUM.SWAMP',
        value: 4,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
      {
        label: 'ENUM.OTHER',
        value: 5,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },
    ];
  
    export const ROLE_IN_HOME =[
      {
        label: 'ENUM.NOT_DO_ANYTHING',
        value: 1,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },  
      {
        label: 'ENUM.PARTIME_JOB',
        value: 2,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      }, 
      {
        label: 'ENUM.HOME_WORK',
        value: 3,
        styleClass: null,
        icon: null,
        title: null,
        disabled: false,
      },  
  ];
  
  export const HOBBIES =[
    {
      label: 'ENUM.SPORT',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },  
    {
      label: 'ENUM.READING',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },  
    {
      label: 'ENUM.PLAY_GAME',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },  
    {
      label: 'ENUM.PLAY_MUSIC',
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
    {
      label: 'ENUM.OTHER',
      value: 5,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },  
  ];
  
  
  export const READ_FREQUENCY =[
    {
      label: 'ENUM.ALWAYS_READ',
      value: 4,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
    {
      label: 'ENUM.BEFORE_TEST',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
    {
      label: 'ENUM.WHEN_TELL',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
    {
      label: 'ENUM.NEVER_READ',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
  ];
  
  
  export const SUPPLIE_STORAGE_FREQUENCY =[
    {
      label: 'ENUM.BEST_STORAGE',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
    {
      label: 'ENUM.GOOD_STORAGE',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
    {
      label: 'ENUM.NEVER_STORAGE',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
  ];
  
  export const WORK_BOOK_CHECKED_FREQUENCY =[
    {
      label: 'ENUM.ALWAYS_CHECK',
      value: 3,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },  
    {
      label: 'ENUM.OFFEN_CHECK',
      value: 2,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },  
    {
      label: 'ENUM.NEVER_CHECK',
      value: 1,
      styleClass: null,
      icon: null,
      title: null,
      disabled: false,
    },   
  ];