GET https://brt-dev.logicspark.com/api/v1/users
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InRlc3QiLCJmaXJzdE5hbWUiOiJOVUxMIiwibGFzdE5hbWUiOiIiLCJ0eXBlQ29kZSI6IiIsImRlcGFydG1lbnRDb2RlIjoiIiwiaWF0IjoxNjQ4MDEzODc4LCJleHAiOjE2NDg2MTg2Nzh9.omlLmFjMOosalxhx2cDj3GCDXIBeIU9XB7LgHeqsd5I