import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { SearchParameter } from "src/core/shared/models/search-param-model";

export class SearchTeacherDto extends SearchParameter {
    title?:number
    firstname?:string
    lastname?:string
    position?:number
}
export class TeacherDto {
    title:number
    firstname:string
    lastname:string
    position:number
    startWork:Date
    role:number
    specialRole:number
    accessDate:Date
    positionCode:string
    range:number
    sarary:number
    birthDate:Date
    personalCode:string
    major:string
    minor:string
    address:string
    countryId:number
    provinceId:number
    districtId:number
    subDistrictId:number
    postCode:string
    contractAddress:string
    contractCountryId:number
    contractProvinceId:number
    contractDistrictId:number
    contractSubDistrictId:number
    contractPostCode:string
    imageProfile:string
} 
export class CreateTeacherDto extends TeacherDto{
    title:number
    firstname:string
    lastname:string
    position:number
    startWork:Date
    role:number
    specialRole:number
    accessDate:Date
    positionCode:string
    range:number
    sarary:number
    birthDate:Date
    personalCode:string
    major:string
    minor:string
    address:string
    countryId:number
    provinceId:number
    districtId:number
    subDistrictId:number
    postCode:string
    contractAddress:string
    contractCountryId:number
    contractProvinceId:number
    contractDistrictId:number
    contractSubDistrictId:number
    contractPostCode:string
    imageProfile:string
}
export class UpdateTeacherDto extends TeacherDto{
    title:number
    firstname:string
    lastname:string
    position:number
    startWork:Date
    role:number
    specialRole:number
    accessDate:Date
    positionCode:string
    range:number
    sarary:number
    birthDate:Date
    personalCode:string
    major:string
    minor:string
    address:string
    countryId:number
    provinceId:number
    districtId:number
    subDistrictId:number
    postCode:string
    contractAddress:string
    contractCountryId:number
    contractProvinceId:number
    contractDistrictId:number
    contractSubDistrictId:number
    contractPostCode:string
    imageProfile:string
}
